let x = 10;

try {
  x = 2;
} catch (error) {
  console.log(`[ERROR] ${error}`);
}
